# Site settings
title: CoprHD Project
email: webmaster@coprhd.org
url: https://coprhd.org
description: "Coprhd is..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#FF6A00'

# Footer settings
footer: EMC Corporation, All rights reserved.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/coprhd
  
  
  - title: github
    url: https://github.com/CoprHD/coprhd-controller

# Build settings
markdown: kramdown
permalink: pretty
